const name = "Keshia Erasia"
const id = 0
const avatar = preload("res://Graphics/UI/Avatar/Keshia Erasia.png")
const points = ["Tanky", "Melee", "Can Erase"]
const full_health = 311
const ghost_health = 604
const movement_speed = 400.0
const jump_height = 300.0
const time_to_jump_to_highest = 0.5
const hurt_modulate_color = Color(255.0 / 255.0, 170.0 / 255.0, 170.0 / 255.0)
const hurt_modulate_node_path = ["Sprite/Animation/Body"]
const ult_eyes_node_path = "Sprite/Animation/Body/Face/Ult Eyes"
const eyes_node_path = ["Sprite/Animation/Body/Face/Left Eye", "Sprite/Animation/Body/Face/Right Eye"]
const fire_particle_node_path = "Sprite/Animation/Body/Fire Particle"
const default_animator_path = "Sprite/AnimationPlayer"
const drink_sprite_path = "Sprite/Animation/Drink"