const name = "Ranawato Plato"
const id = 2
const avatar = preload("res://Graphics/UI/Avatar/Ranawato Plato.png")
const points = ["Accurate", "Fragile", "T r a n q u i l"]
const full_health = 244
const ghost_health = 704
const movement_speed = 300.0
const jump_height = 300.0
const time_to_jump_to_highest = 0.8
const hurt_modulate_color = Color(1.0, 215.0 / 255.0, 215.0 / 255.0)
const hurt_modulate_node_path = ["Sprite/Animation/Body"]
const ult_eyes_node_path = "Sprite/Animation/Body/Face/UltEyes"
const eyes_node_path = ["Sprite/Animation/Body/Face/Left Eye", "Sprite/Animation/Body/Face/Right Eye"]
const fire_particle_node_path = "Sprite/Animation/Body/Fire Particle"
const default_animator_path = "Sprite/AnimationPlayer"
const drink_sprite_path = "Sprite/Animation/Body/Right Arm/Drink"