const name = "Wendy Floopy"
const id = 1
const avatar = preload("res://Graphics/UI/Avatar/Wendy Vista.png")
const points = ["Long Ranged", "Fragile", "Cute"]
const full_health = 228
const ghost_health = 744
const movement_speed = 350.0
const jump_height = 300.0
const time_to_jump_to_highest = 0.65
const hurt_modulate_color = Color(255.0 / 255.0, 150.0 / 255.0, 150.0 / 255.0)
const hurt_modulate_node_path = ["Sprite/Animation/Body"]
const ult_eyes_node_path = "Sprite/Animation/Body/UltEyes"
const eyes_node_path = ["Sprite/Animation/Body/Eye", "Sprite/Animation/Body/Eye Lashes"]
const fire_particle_node_path = "Sprite/Animation/Body/Fire Particle"
const default_animator_path = "Sprite/AnimationPlayer"
const drink_sprite_path = "Sprite/Animation/Drink"